#!/usr/bin/env python

import os
import glob
import sys
import socket
import hashlib

sys.path.append('gen-py')
sys.path.insert(0, glob.glob('/home/yaoliu/src_code/local/lib/lib/python2.7/site-packages/')[0])

from chord import FileStore
from chord.ttypes import SystemException, RFileMetadata, RFile, NodeID
from thrift.transport import TSocket
from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol
from thrift.server import TServer

if __name__ == '__main__':
    meta = RFileMetadata("hello.txt", 5, "guest", "asdf")
    rfile = RFile(meta, "Hello World!")

    transport = TSocket.TSocket("remote02.cs.binghamton.edu", "9092")
    protocol = TBinaryProtocol.TBinaryProtocol(transport)
    chordClient = FileStore.Client(protocol)
    transport.open()
    chordClient.writeFile(rfile)
    print "File written successfully"